### ISSUE TITLE
Oauth GetAccessToken

### ISSUE THREAD

**Issue by jreyt** [globelabs/globe-connect-php#1]
this should be a post request.

globe-connect-php/src/Globe/Connect/Oauth.php

      public function getAccessToken() {
        // check if code is set
        if(!isset($this->params['code'])) {
            // throw exception if code is not set
            throw new \Exception('`code` is required');
        }

        // prepare request url
        $url = sprintf(self::TOKEN_URL, $this->params['key'], $this->params['secret'], $this->params['code']);
        
        // intialize custom curl
        $curl = new Curl();
        // prepare get request
        $curl->get($url);
        // return curl response
        return $curl->exec();
    }

working code below.

        public function getAccessToken() {
             // check if code is set
            if(!isset($this->params['code'])) {
            // throw exception if code is not set
            throw new \Exception('`code` is required');
          }
        
        // prepare request url
        $url = sprintf(self::TOKEN_URL, $this->params['key'], $this->params['secret'], $this->params['code']);
        
        // intialize custom curl
        $curl = new Curl();
        $curl->setHeader(array('Content-type: application/json'));
        // prepare get request
        $curl->post($url);
        // return curl response
        return $curl->exec();

    }

**Comment by cjzamora** [comment]
This is already fixed.
