### ISSUE TITLE
ERROR Undefined Variable smsRequired

### ISSUE THREAD

**Issue by jreyt** [globelabs/globe-connect-php#2]
> // loop sms required fields
>         foreach(**$smsRequired** as $v) {
>             // check if required fields are set
>             if(!isset($this->params[$v])) {
>                 // throw new exception if a required field is not set
>                 throw new \Exception('`'. $v .'` is required.');
>             }
>         }

This should be $this->smsRequired.

**Comment by cjzamora** [comment]
This is already fixed. 1b808e26526549e3edfb7818060d93cf57cbc9d7
